<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8"/>
		<script src="https://cdn.rebilly.com/instruments/@latest/core.js" type="text/javascript"></script>
		<title>Phronesis 3</title>
		<meta name="viewport" content="width=device-width,initial-scale=1"/>
		<style>
			body, html {
			  background: #291711;
			  padding: 0;
			  margin: 0;
			}

			body {
				display: flex;
				justify-content: center;
			}

			#app {
			  font-family: Trebuchet MS, sans-serif;
			  -webkit-font-smoothing: antialiased;
			  -moz-osx-font-smoothing: grayscale;
			  text-align: center;
			  color: #ffffff;
			}

			#app a {
			  color: #ffffff;
			}

			.form-wrapper {
			  max-width: 700px;
			  min-width: 500px;
			  box-sizing: border-box;
			  padding: 40px 0;
			  margin: 0 auto;
			}

			.form-wrapper section {
			  background: transparent;
			  box-sizing: border-box;
			  padding: 40px;
			  border-radius: 6px;
			  border: 1px solid rgba(255,255,255,0.25);
			}

			.form-wrapper section + section {
			  margin-top: 20px;
			}

			.period-switch {
				display: flex;
				flex-flow: row;
				justify-content: center;
				gap: 4pt;
				font-size: 14pt;
			}

			.period-switch input[type="checkbox"] {
				display: none;
			}

			.period-switch .period-toggle {
				position: relative;
				display: inline-block;
				border-radius: 10px;
				width: 28pt;
				height: 14pt;
				border: 1px solid rgba(255,255,255,0.25);
			}

			.period-switch .period-toggle::before {
				content: '';
				position: absolute;
				top: 0;
				left: 0;
				width: 14pt;
				height: 14pt;
				border-radius: 100%;;
				background-color: #5FBB97;
				transition: all .3s ease-in-out;
			}

			.period-switch input[type="checkbox"]:checked ~ .period-toggle::before {
				left: 18px;
			}

			.display-none {
				display: none;
			}
		</style>
	</head>
	<body id="app">
		<div class="form-wrapper">
			<form method="POST" action="/donate">
				<div>
                    <label for="amount">Amount</label>
				    <input type="number" id="amount" name="amount" required />
                </div>
                <div>
				    <label for="recurring">Make it monthly</label>
                    <input type="checkbox" id="recurring" name="recurring" value="1" />
                </div>
                <div>
                    <label for="email">Email</label>
                    <input type="email" id="email" name="email" required />
                </div>
				<input type="submit" name="submit" value="Make a donation" />
			</form>
	    </div>
	</body>
</html>
